# Generated by Django 5.0.3 on 2024-03-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='Category',
            new_name='category',
        ),
    ]
